### ISSUE TITLE
HR Modify Point Total Interface

### ISSUE THREAD

**Issue by mharris9180** [F17MIS4173Team3/Apex#13]
@jasongreb I am logged in as "admin" and do not see where to modify an employee's point total.  Has that interface been developed or am I missing it?

**Comment by jasongreb** [comment]
There shouldn't be a "modify" of the balance, it should be able to add to it, and approve any new ones that come in. I haven't built the approval interface yet.

**Comment by jasongreb** [comment]
Approval interface has been built, and HR can submit for another user.
