### ISSUE TITLE
Employee Makes Submisssion

### ISSUE THREAD

**Issue by millerdan14** [F17MIS4173Team3/Apex#14]
@jasongreb The "New Submission" Activity Type contains 3 activities.  What is your plan for how points are acquired and accumulated?

**Comment by jasongreb** [comment]
I haven't added them all yet. Waiting for commentary from David on the Activity Types page in OneNote.

**Comment by jasongreb** [comment]
All activities have been entered except for "Nutrition". Will add that later if felt it should be added. Requires a bit more code due to the daily limits.
