### ISSUE TITLE
New Submission Calendar

### ISSUE THREAD

**Issue by millerdan14** [F17MIS4173Team3/Apex#19]
Hi Jason,

Just a minor annoyance.  The calendar does not have a little arrow to move between months.  I have found that if you manually enter a date, it will take the user to that month.  Could this be added?

**Comment by millerdan14** [comment]
Actually, I found the arrows to move from one month to another but they are hidden.   See below

![image](https://user-images.githubusercontent.com/31518215/32173003-e8e27cc2-bd53-11e7-894b-ee9b42400c9a.png)

**Comment by jasongreb** [comment]
I can confirm this is an issue. There should be arrows there, may just be an image issue in jQuery UI. I will look into it.

**Comment by jasongreb** [comment]
This has been resolved by uploading the jQuery images for the datepicker.
