### ISSUE TITLE
New Submission with Attachment - No Confirmation Chrome

### ISSUE THREAD

**Issue by mharris9180** [F17MIS4173Team3/Apex#20]
When I submitted an item with an attachment in Chrome, it sent me to a blank New Submission page.  I did check and it recorded the submission in my history

**Comment by jasongreb** [comment]
Do you remember which item in the drop down it did this for? It might have something to do with the "approval". I might just have neglected to have a message when approval is not needed.

**Comment by jasongreb** [comment]
This is resolved now by moving some if blocks around.
