### ISSUE TITLE
Admin Wellness History - User

### ISSUE THREAD

**Issue by mharris9180** [F17MIS4173Team3/Apex#22]
Logged in as admin, should there be a column that indicates who the submission is for under Wellness History?  Now it has Date, Activity, Data, Points, Approved.

**Comment by jasongreb** [comment]
That history is currently their own history. I have a task to add a drop down that shows other users, just haven't gotten it in there yet.

**Comment by jasongreb** [comment]
Closing this since it is duplicate of issue #18
