### ISSUE TITLE
Login form is no longer verifying

### ISSUE THREAD

**Issue by jasongreb** [F17MIS4173Team3/Apex#3]
Any login with any password is allowing the user into the system. It still reads between admin and regular employee however, so likely an issue with password verification only.

**Comment by millerdan14** [comment]
In the course of testing, this is still an issue.  Like it is supposed to, the admin screen only appears when the "admin" username is used.  All other usernames take user to normal user screen.  "Welcome -1" is displayed in the top-right corner of the screen when an invalid username is used.

**Comment by jasongreb** [comment]
Corrected this by changing a single = to the double ==.
